channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - matplotlib
  - pandas
  - geopandas
  - pytz
  - scikit-image
  - scikit-learn=0.20.3
  - astropy
  - gdal
  - shapely
  - scipy
  - pyproj
  - pykrige
  - cartopy
  - pyfftw
  - rasterio
  - arosics
  - notebook
  - spyder
  - PyQtWebEngine 